# SPDX-License-Identifier: MIT; Copyright 2026 Andrew D Smith

install(TARGETS falco RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

list(
  TRANSFORM FastQC_DATA_FILES
  PREPEND "${BUILD_DATA_DIR}/"
  OUTPUT_VARIABLE FastQC_DATA_PATHS
)

install(
  FILES
  ${FastQC_DATA_PATHS}
  DESTINATION
  ${CMAKE_INSTALL_DATADIR}/falco
)
